/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AsesorRouteImport } from './routes/asesor'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as HerramientasRouteImport } from './routes/herramientas'
import { Route as MonitorMercadoRouteImport } from './routes/monitor-mercado'
import { Route as PlanificacionRouteImport } from './routes/planificacion'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as ApiSugerenciasRouteImport } from './routes/api/sugerencias'
import { Route as ApiTelegramRouteImport } from './routes/api/telegram'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AsesorRoute = AsesorRouteImport.update({
  id: '/asesor',
  path: '/asesor',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const HerramientasRoute = HerramientasRouteImport.update({
  id: '/herramientas',
  path: '/herramientas',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitorMercadoRoute = MonitorMercadoRouteImport.update({
  id: '/monitor-mercado',
  path: '/monitor-mercado',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanificacionRoute = PlanificacionRouteImport.update({
  id: '/planificacion',
  path: '/planificacion',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSugerenciasRoute = ApiSugerenciasRouteImport.update({
  id: '/api/sugerencias',
  path: '/api/sugerencias',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTelegramRoute = ApiTelegramRouteImport.update({
  id: '/api/telegram',
  path: '/api/telegram',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/asesor': typeof AsesorRoute
  '/contacto': typeof ContactoRoute
  '/demo': typeof DemoRoute
  '/herramientas': typeof HerramientasRoute
  '/monitor-mercado': typeof MonitorMercadoRoute
  '/planificacion': typeof PlanificacionRoute
  '/studio': typeof StudioRoute
  '/api/chat': typeof ApiChatRoute
  '/api/search': typeof ApiSearchRoute
  '/api/sugerencias': typeof ApiSugerenciasRoute
  '/api/telegram': typeof ApiTelegramRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/asesor': typeof AsesorRoute
  '/contacto': typeof ContactoRoute
  '/demo': typeof DemoRoute
  '/herramientas': typeof HerramientasRoute
  '/monitor-mercado': typeof MonitorMercadoRoute
  '/planificacion': typeof PlanificacionRoute
  '/studio': typeof StudioRoute
  '/api/chat': typeof ApiChatRoute
  '/api/search': typeof ApiSearchRoute
  '/api/sugerencias': typeof ApiSugerenciasRoute
  '/api/telegram': typeof ApiTelegramRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/asesor': typeof AsesorRoute
  '/contacto': typeof ContactoRoute
  '/demo': typeof DemoRoute
  '/herramientas': typeof HerramientasRoute
  '/monitor-mercado': typeof MonitorMercadoRoute
  '/planificacion': typeof PlanificacionRoute
  '/studio': typeof StudioRoute
  '/api/chat': typeof ApiChatRoute
  '/api/search': typeof ApiSearchRoute
  '/api/sugerencias': typeof ApiSugerenciasRoute
  '/api/telegram': typeof ApiTelegramRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/asesor'
    | '/contacto'
    | '/demo'
    | '/herramientas'
    | '/monitor-mercado'
    | '/planificacion'
    | '/studio'
    | '/api/chat'
    | '/api/search'
    | '/api/sugerencias'
    | '/api/telegram'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/asesor'
    | '/contacto'
    | '/demo'
    | '/herramientas'
    | '/monitor-mercado'
    | '/planificacion'
    | '/studio'
    | '/api/chat'
    | '/api/search'
    | '/api/sugerencias'
    | '/api/telegram'
  id:
    | '__root__'
    | '/'
    | '/asesor'
    | '/contacto'
    | '/demo'
    | '/herramientas'
    | '/monitor-mercado'
    | '/planificacion'
    | '/studio'
    | '/api/chat'
    | '/api/search'
    | '/api/sugerencias'
    | '/api/telegram'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AsesorRoute: typeof AsesorRoute
  ContactoRoute: typeof ContactoRoute
  DemoRoute: typeof DemoRoute
  HerramientasRoute: typeof HerramientasRoute
  MonitorMercadoRoute: typeof MonitorMercadoRoute
  PlanificacionRoute: typeof PlanificacionRoute
  StudioRoute: typeof StudioRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiSearchRoute: typeof ApiSearchRoute
  ApiSugerenciasRoute: typeof ApiSugerenciasRoute
  ApiTelegramRoute: typeof ApiTelegramRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asesor': {
      id: '/asesor'
      path: '/asesor'
      fullPath: '/asesor'
      preLoaderRoute: typeof AsesorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/herramientas': {
      id: '/herramientas'
      path: '/herramientas'
      fullPath: '/herramientas'
      preLoaderRoute: typeof HerramientasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitor-mercado': {
      id: '/monitor-mercado'
      path: '/monitor-mercado'
      fullPath: '/monitor-mercado'
      preLoaderRoute: typeof MonitorMercadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planificacion': {
      id: '/planificacion'
      path: '/planificacion'
      fullPath: '/planificacion'
      preLoaderRoute: typeof PlanificacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sugerencias': {
      id: '/api/sugerencias'
      path: '/api/sugerencias'
      fullPath: '/api/sugerencias'
      preLoaderRoute: typeof ApiSugerenciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/telegram': {
      id: '/api/telegram'
      path: '/api/telegram'
      fullPath: '/api/telegram'
      preLoaderRoute: typeof ApiTelegramRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AsesorRoute: AsesorRoute,
  ContactoRoute: ContactoRoute,
  DemoRoute: DemoRoute,
  HerramientasRoute: HerramientasRoute,
  MonitorMercadoRoute: MonitorMercadoRoute,
  PlanificacionRoute: PlanificacionRoute,
  StudioRoute: StudioRoute,
  ApiChatRoute: ApiChatRoute,
  ApiSearchRoute: ApiSearchRoute,
  ApiSugerenciasRoute: ApiSugerenciasRoute,
  ApiTelegramRoute: ApiTelegramRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
