/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AsesorRouteImport } from './routes/asesor'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as HerramientasRouteImport } from './routes/herramientas'
import { Route as MonitorMercadoRouteImport } from './routes/monitor-mercado'
import { Route as PlanificacionRouteImport } from './routes/planificacion'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as ApiBotUnificadoRouteImport } from './routes/api/bot-unificado'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiPrediccionRouteImport } from './routes/api/prediccion'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as ApiSugerenciasRouteImport } from './routes/api/sugerencias'
import { Route as ApiTelegramRouteImport } from './routes/api/telegram'
import { Route as ApiCronActualizaRentaFijaRouteImport } from './routes/api/cron/actualiza-renta-fija'
import { Route as ApiCronAlertaPublicacionesRouteImport } from './routes/api/cron/alerta-publicaciones'
import { Route as ApiCronContextoTelegramRouteImport } from './routes/api/cron/contexto-telegram'
import { Route as ApiCronEarningsSemanalRouteImport } from './routes/api/cron/earnings-semanal'
import { Route as ApiCronOportunidadesPublicacionesRouteImport } from './routes/api/cron/oportunidades-publicaciones'
import { Route as ApiCronScannerSenalesRouteImport } from './routes/api/cron/scanner-senales'
import { Route as ApiCronSenalesUnificadasRouteImport } from './routes/api/cron/senales-unificadas'
import { Route as ApiCronTuningSenalesRouteImport } from './routes/api/cron/tuning-senales'
import { Route as ApiIolStatusRouteImport } from './routes/api/iol.status'
import { Route as ApiOpcionesCadenaRouteImport } from './routes/api/opciones.cadena'
import { Route as ApiOpcionesPrecioRouteImport } from './routes/api/opciones.precio'
import { Route as ApiTelegramWebhookRouteImport } from './routes/api/telegram/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AsesorRoute = AsesorRouteImport.update({
  id: '/asesor',
  path: '/asesor',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const HerramientasRoute = HerramientasRouteImport.update({
  id: '/herramientas',
  path: '/herramientas',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitorMercadoRoute = MonitorMercadoRouteImport.update({
  id: '/monitor-mercado',
  path: '/monitor-mercado',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanificacionRoute = PlanificacionRouteImport.update({
  id: '/planificacion',
  path: '/planificacion',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBotUnificadoRoute = ApiBotUnificadoRouteImport.update({
  id: '/api/bot-unificado',
  path: '/api/bot-unificado',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPrediccionRoute = ApiPrediccionRouteImport.update({
  id: '/api/prediccion',
  path: '/api/prediccion',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSugerenciasRoute = ApiSugerenciasRouteImport.update({
  id: '/api/sugerencias',
  path: '/api/sugerencias',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTelegramRoute = ApiTelegramRouteImport.update({
  id: '/api/telegram',
  path: '/api/telegram',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronActualizaRentaFijaRoute =
  ApiCronActualizaRentaFijaRouteImport.update({
    id: '/api/cron/actualiza-renta-fija',
    path: '/api/cron/actualiza-renta-fija',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCronAlertaPublicacionesRoute =
  ApiCronAlertaPublicacionesRouteImport.update({
    id: '/api/cron/alerta-publicaciones',
    path: '/api/cron/alerta-publicaciones',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCronContextoTelegramRoute = ApiCronContextoTelegramRouteImport.update({
  id: '/api/cron/contexto-telegram',
  path: '/api/cron/contexto-telegram',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronEarningsSemanalRoute = ApiCronEarningsSemanalRouteImport.update({
  id: '/api/cron/earnings-semanal',
  path: '/api/cron/earnings-semanal',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronOportunidadesPublicacionesRoute =
  ApiCronOportunidadesPublicacionesRouteImport.update({
    id: '/api/cron/oportunidades-publicaciones',
    path: '/api/cron/oportunidades-publicaciones',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCronScannerSenalesRoute = ApiCronScannerSenalesRouteImport.update({
  id: '/api/cron/scanner-senales',
  path: '/api/cron/scanner-senales',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronSenalesUnificadasRoute =
  ApiCronSenalesUnificadasRouteImport.update({
    id: '/api/cron/senales-unificadas',
    path: '/api/cron/senales-unificadas',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCronTuningSenalesRoute = ApiCronTuningSenalesRouteImport.update({
  id: '/api/cron/tuning-senales',
  path: '/api/cron/tuning-senales',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIolStatusRoute = ApiIolStatusRouteImport.update({
  id: '/api/iol/status',
  path: '/api/iol/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpcionesCadenaRoute = ApiOpcionesCadenaRouteImport.update({
  id: '/api/opciones/cadena',
  path: '/api/opciones/cadena',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpcionesPrecioRoute = ApiOpcionesPrecioRouteImport.update({
  id: '/api/opciones/precio',
  path: '/api/opciones/precio',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTelegramWebhookRoute = ApiTelegramWebhookRouteImport.update({
  id: '/webhook',
  path: '/webhook',
  getParentRoute: () => ApiTelegramRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/asesor': typeof AsesorRoute
  '/contacto': typeof ContactoRoute
  '/demo': typeof DemoRoute
  '/herramientas': typeof HerramientasRoute
  '/monitor-mercado': typeof MonitorMercadoRoute
  '/planificacion': typeof PlanificacionRoute
  '/studio': typeof StudioRoute
  '/api/bot-unificado': typeof ApiBotUnificadoRoute
  '/api/chat': typeof ApiChatRoute
  '/api/prediccion': typeof ApiPrediccionRoute
  '/api/search': typeof ApiSearchRoute
  '/api/sugerencias': typeof ApiSugerenciasRoute
  '/api/telegram': typeof ApiTelegramRouteWithChildren
  '/api/cron/actualiza-renta-fija': typeof ApiCronActualizaRentaFijaRoute
  '/api/cron/alerta-publicaciones': typeof ApiCronAlertaPublicacionesRoute
  '/api/cron/contexto-telegram': typeof ApiCronContextoTelegramRoute
  '/api/cron/earnings-semanal': typeof ApiCronEarningsSemanalRoute
  '/api/cron/oportunidades-publicaciones': typeof ApiCronOportunidadesPublicacionesRoute
  '/api/cron/scanner-senales': typeof ApiCronScannerSenalesRoute
  '/api/cron/senales-unificadas': typeof ApiCronSenalesUnificadasRoute
  '/api/cron/tuning-senales': typeof ApiCronTuningSenalesRoute
  '/api/iol/status': typeof ApiIolStatusRoute
  '/api/opciones/cadena': typeof ApiOpcionesCadenaRoute
  '/api/opciones/precio': typeof ApiOpcionesPrecioRoute
  '/api/telegram/webhook': typeof ApiTelegramWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/asesor': typeof AsesorRoute
  '/contacto': typeof ContactoRoute
  '/demo': typeof DemoRoute
  '/herramientas': typeof HerramientasRoute
  '/monitor-mercado': typeof MonitorMercadoRoute
  '/planificacion': typeof PlanificacionRoute
  '/studio': typeof StudioRoute
  '/api/bot-unificado': typeof ApiBotUnificadoRoute
  '/api/chat': typeof ApiChatRoute
  '/api/prediccion': typeof ApiPrediccionRoute
  '/api/search': typeof ApiSearchRoute
  '/api/sugerencias': typeof ApiSugerenciasRoute
  '/api/telegram': typeof ApiTelegramRouteWithChildren
  '/api/cron/actualiza-renta-fija': typeof ApiCronActualizaRentaFijaRoute
  '/api/cron/alerta-publicaciones': typeof ApiCronAlertaPublicacionesRoute
  '/api/cron/contexto-telegram': typeof ApiCronContextoTelegramRoute
  '/api/cron/earnings-semanal': typeof ApiCronEarningsSemanalRoute
  '/api/cron/oportunidades-publicaciones': typeof ApiCronOportunidadesPublicacionesRoute
  '/api/cron/scanner-senales': typeof ApiCronScannerSenalesRoute
  '/api/cron/senales-unificadas': typeof ApiCronSenalesUnificadasRoute
  '/api/cron/tuning-senales': typeof ApiCronTuningSenalesRoute
  '/api/iol/status': typeof ApiIolStatusRoute
  '/api/opciones/cadena': typeof ApiOpcionesCadenaRoute
  '/api/opciones/precio': typeof ApiOpcionesPrecioRoute
  '/api/telegram/webhook': typeof ApiTelegramWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/asesor': typeof AsesorRoute
  '/contacto': typeof ContactoRoute
  '/demo': typeof DemoRoute
  '/herramientas': typeof HerramientasRoute
  '/monitor-mercado': typeof MonitorMercadoRoute
  '/planificacion': typeof PlanificacionRoute
  '/studio': typeof StudioRoute
  '/api/bot-unificado': typeof ApiBotUnificadoRoute
  '/api/chat': typeof ApiChatRoute
  '/api/prediccion': typeof ApiPrediccionRoute
  '/api/search': typeof ApiSearchRoute
  '/api/sugerencias': typeof ApiSugerenciasRoute
  '/api/telegram': typeof ApiTelegramRouteWithChildren
  '/api/cron/actualiza-renta-fija': typeof ApiCronActualizaRentaFijaRoute
  '/api/cron/alerta-publicaciones': typeof ApiCronAlertaPublicacionesRoute
  '/api/cron/contexto-telegram': typeof ApiCronContextoTelegramRoute
  '/api/cron/earnings-semanal': typeof ApiCronEarningsSemanalRoute
  '/api/cron/oportunidades-publicaciones': typeof ApiCronOportunidadesPublicacionesRoute
  '/api/cron/scanner-senales': typeof ApiCronScannerSenalesRoute
  '/api/cron/senales-unificadas': typeof ApiCronSenalesUnificadasRoute
  '/api/cron/tuning-senales': typeof ApiCronTuningSenalesRoute
  '/api/iol/status': typeof ApiIolStatusRoute
  '/api/opciones/cadena': typeof ApiOpcionesCadenaRoute
  '/api/opciones/precio': typeof ApiOpcionesPrecioRoute
  '/api/telegram/webhook': typeof ApiTelegramWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/asesor'
    | '/contacto'
    | '/demo'
    | '/herramientas'
    | '/monitor-mercado'
    | '/planificacion'
    | '/studio'
    | '/api/bot-unificado'
    | '/api/chat'
    | '/api/prediccion'
    | '/api/search'
    | '/api/sugerencias'
    | '/api/telegram'
    | '/api/cron/actualiza-renta-fija'
    | '/api/cron/alerta-publicaciones'
    | '/api/cron/contexto-telegram'
    | '/api/cron/earnings-semanal'
    | '/api/cron/oportunidades-publicaciones'
    | '/api/cron/scanner-senales'
    | '/api/cron/senales-unificadas'
    | '/api/cron/tuning-senales'
    | '/api/iol/status'
    | '/api/opciones/cadena'
    | '/api/opciones/precio'
    | '/api/telegram/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/asesor'
    | '/contacto'
    | '/demo'
    | '/herramientas'
    | '/monitor-mercado'
    | '/planificacion'
    | '/studio'
    | '/api/bot-unificado'
    | '/api/chat'
    | '/api/prediccion'
    | '/api/search'
    | '/api/sugerencias'
    | '/api/telegram'
    | '/api/cron/actualiza-renta-fija'
    | '/api/cron/alerta-publicaciones'
    | '/api/cron/contexto-telegram'
    | '/api/cron/earnings-semanal'
    | '/api/cron/oportunidades-publicaciones'
    | '/api/cron/scanner-senales'
    | '/api/cron/senales-unificadas'
    | '/api/cron/tuning-senales'
    | '/api/iol/status'
    | '/api/opciones/cadena'
    | '/api/opciones/precio'
    | '/api/telegram/webhook'
  id:
    | '__root__'
    | '/'
    | '/asesor'
    | '/contacto'
    | '/demo'
    | '/herramientas'
    | '/monitor-mercado'
    | '/planificacion'
    | '/studio'
    | '/api/bot-unificado'
    | '/api/chat'
    | '/api/prediccion'
    | '/api/search'
    | '/api/sugerencias'
    | '/api/telegram'
    | '/api/cron/actualiza-renta-fija'
    | '/api/cron/alerta-publicaciones'
    | '/api/cron/contexto-telegram'
    | '/api/cron/earnings-semanal'
    | '/api/cron/oportunidades-publicaciones'
    | '/api/cron/scanner-senales'
    | '/api/cron/senales-unificadas'
    | '/api/cron/tuning-senales'
    | '/api/iol/status'
    | '/api/opciones/cadena'
    | '/api/opciones/precio'
    | '/api/telegram/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AsesorRoute: typeof AsesorRoute
  ContactoRoute: typeof ContactoRoute
  DemoRoute: typeof DemoRoute
  HerramientasRoute: typeof HerramientasRoute
  MonitorMercadoRoute: typeof MonitorMercadoRoute
  PlanificacionRoute: typeof PlanificacionRoute
  StudioRoute: typeof StudioRoute
  ApiBotUnificadoRoute: typeof ApiBotUnificadoRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiPrediccionRoute: typeof ApiPrediccionRoute
  ApiSearchRoute: typeof ApiSearchRoute
  ApiSugerenciasRoute: typeof ApiSugerenciasRoute
  ApiTelegramRoute: typeof ApiTelegramRouteWithChildren
  ApiCronActualizaRentaFijaRoute: typeof ApiCronActualizaRentaFijaRoute
  ApiCronAlertaPublicacionesRoute: typeof ApiCronAlertaPublicacionesRoute
  ApiCronContextoTelegramRoute: typeof ApiCronContextoTelegramRoute
  ApiCronEarningsSemanalRoute: typeof ApiCronEarningsSemanalRoute
  ApiCronOportunidadesPublicacionesRoute: typeof ApiCronOportunidadesPublicacionesRoute
  ApiCronScannerSenalesRoute: typeof ApiCronScannerSenalesRoute
  ApiCronSenalesUnificadasRoute: typeof ApiCronSenalesUnificadasRoute
  ApiCronTuningSenalesRoute: typeof ApiCronTuningSenalesRoute
  ApiIolStatusRoute: typeof ApiIolStatusRoute
  ApiOpcionesCadenaRoute: typeof ApiOpcionesCadenaRoute
  ApiOpcionesPrecioRoute: typeof ApiOpcionesPrecioRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asesor': {
      id: '/asesor'
      path: '/asesor'
      fullPath: '/asesor'
      preLoaderRoute: typeof AsesorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/herramientas': {
      id: '/herramientas'
      path: '/herramientas'
      fullPath: '/herramientas'
      preLoaderRoute: typeof HerramientasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitor-mercado': {
      id: '/monitor-mercado'
      path: '/monitor-mercado'
      fullPath: '/monitor-mercado'
      preLoaderRoute: typeof MonitorMercadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planificacion': {
      id: '/planificacion'
      path: '/planificacion'
      fullPath: '/planificacion'
      preLoaderRoute: typeof PlanificacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bot-unificado': {
      id: '/api/bot-unificado'
      path: '/api/bot-unificado'
      fullPath: '/api/bot-unificado'
      preLoaderRoute: typeof ApiBotUnificadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/prediccion': {
      id: '/api/prediccion'
      path: '/api/prediccion'
      fullPath: '/api/prediccion'
      preLoaderRoute: typeof ApiPrediccionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sugerencias': {
      id: '/api/sugerencias'
      path: '/api/sugerencias'
      fullPath: '/api/sugerencias'
      preLoaderRoute: typeof ApiSugerenciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/telegram': {
      id: '/api/telegram'
      path: '/api/telegram'
      fullPath: '/api/telegram'
      preLoaderRoute: typeof ApiTelegramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/actualiza-renta-fija': {
      id: '/api/cron/actualiza-renta-fija'
      path: '/api/cron/actualiza-renta-fija'
      fullPath: '/api/cron/actualiza-renta-fija'
      preLoaderRoute: typeof ApiCronActualizaRentaFijaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/alerta-publicaciones': {
      id: '/api/cron/alerta-publicaciones'
      path: '/api/cron/alerta-publicaciones'
      fullPath: '/api/cron/alerta-publicaciones'
      preLoaderRoute: typeof ApiCronAlertaPublicacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/contexto-telegram': {
      id: '/api/cron/contexto-telegram'
      path: '/api/cron/contexto-telegram'
      fullPath: '/api/cron/contexto-telegram'
      preLoaderRoute: typeof ApiCronContextoTelegramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/earnings-semanal': {
      id: '/api/cron/earnings-semanal'
      path: '/api/cron/earnings-semanal'
      fullPath: '/api/cron/earnings-semanal'
      preLoaderRoute: typeof ApiCronEarningsSemanalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/oportunidades-publicaciones': {
      id: '/api/cron/oportunidades-publicaciones'
      path: '/api/cron/oportunidades-publicaciones'
      fullPath: '/api/cron/oportunidades-publicaciones'
      preLoaderRoute: typeof ApiCronOportunidadesPublicacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/scanner-senales': {
      id: '/api/cron/scanner-senales'
      path: '/api/cron/scanner-senales'
      fullPath: '/api/cron/scanner-senales'
      preLoaderRoute: typeof ApiCronScannerSenalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/senales-unificadas': {
      id: '/api/cron/senales-unificadas'
      path: '/api/cron/senales-unificadas'
      fullPath: '/api/cron/senales-unificadas'
      preLoaderRoute: typeof ApiCronSenalesUnificadasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/tuning-senales': {
      id: '/api/cron/tuning-senales'
      path: '/api/cron/tuning-senales'
      fullPath: '/api/cron/tuning-senales'
      preLoaderRoute: typeof ApiCronTuningSenalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/iol/status': {
      id: '/api/iol/status'
      path: '/api/iol/status'
      fullPath: '/api/iol/status'
      preLoaderRoute: typeof ApiIolStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/opciones/cadena': {
      id: '/api/opciones/cadena'
      path: '/api/opciones/cadena'
      fullPath: '/api/opciones/cadena'
      preLoaderRoute: typeof ApiOpcionesCadenaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/opciones/precio': {
      id: '/api/opciones/precio'
      path: '/api/opciones/precio'
      fullPath: '/api/opciones/precio'
      preLoaderRoute: typeof ApiOpcionesPrecioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/telegram/webhook': {
      id: '/api/telegram/webhook'
      path: '/webhook'
      fullPath: '/api/telegram/webhook'
      preLoaderRoute: typeof ApiTelegramWebhookRouteImport
      parentRoute: typeof ApiTelegramRoute
    }
  }
}

interface ApiTelegramRouteChildren {
  ApiTelegramWebhookRoute: typeof ApiTelegramWebhookRoute
}

const ApiTelegramRouteChildren: ApiTelegramRouteChildren = {
  ApiTelegramWebhookRoute: ApiTelegramWebhookRoute,
}

const ApiTelegramRouteWithChildren = ApiTelegramRoute._addFileChildren(
  ApiTelegramRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AsesorRoute: AsesorRoute,
  ContactoRoute: ContactoRoute,
  DemoRoute: DemoRoute,
  HerramientasRoute: HerramientasRoute,
  MonitorMercadoRoute: MonitorMercadoRoute,
  PlanificacionRoute: PlanificacionRoute,
  StudioRoute: StudioRoute,
  ApiBotUnificadoRoute: ApiBotUnificadoRoute,
  ApiChatRoute: ApiChatRoute,
  ApiPrediccionRoute: ApiPrediccionRoute,
  ApiSearchRoute: ApiSearchRoute,
  ApiSugerenciasRoute: ApiSugerenciasRoute,
  ApiTelegramRoute: ApiTelegramRouteWithChildren,
  ApiCronActualizaRentaFijaRoute: ApiCronActualizaRentaFijaRoute,
  ApiCronAlertaPublicacionesRoute: ApiCronAlertaPublicacionesRoute,
  ApiCronContextoTelegramRoute: ApiCronContextoTelegramRoute,
  ApiCronEarningsSemanalRoute: ApiCronEarningsSemanalRoute,
  ApiCronOportunidadesPublicacionesRoute:
    ApiCronOportunidadesPublicacionesRoute,
  ApiCronScannerSenalesRoute: ApiCronScannerSenalesRoute,
  ApiCronSenalesUnificadasRoute: ApiCronSenalesUnificadasRoute,
  ApiCronTuningSenalesRoute: ApiCronTuningSenalesRoute,
  ApiIolStatusRoute: ApiIolStatusRoute,
  ApiOpcionesCadenaRoute: ApiOpcionesCadenaRoute,
  ApiOpcionesPrecioRoute: ApiOpcionesPrecioRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
