/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AsesorRouteImport } from './routes/asesor'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as ApiSugerenciasRouteImport } from './routes/api/sugerencias'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AsesorRoute = AsesorRouteImport.update({
  id: '/asesor',
  path: '/asesor',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSugerenciasRoute = ApiSugerenciasRouteImport.update({
  id: '/api/sugerencias',
  path: '/api/sugerencias',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/asesor': typeof AsesorRoute
  '/api/chat': typeof ApiChatRoute
  '/api/search': typeof ApiSearchRoute
  '/api/sugerencias': typeof ApiSugerenciasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/asesor': typeof AsesorRoute
  '/api/chat': typeof ApiChatRoute
  '/api/search': typeof ApiSearchRoute
  '/api/sugerencias': typeof ApiSugerenciasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/asesor': typeof AsesorRoute
  '/api/chat': typeof ApiChatRoute
  '/api/search': typeof ApiSearchRoute
  '/api/sugerencias': typeof ApiSugerenciasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/asesor' | '/api/chat' | '/api/search' | '/api/sugerencias'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/asesor' | '/api/chat' | '/api/search' | '/api/sugerencias'
  id:
    | '__root__'
    | '/'
    | '/asesor'
    | '/api/chat'
    | '/api/search'
    | '/api/sugerencias'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AsesorRoute: typeof AsesorRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiSearchRoute: typeof ApiSearchRoute
  ApiSugerenciasRoute: typeof ApiSugerenciasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asesor': {
      id: '/asesor'
      path: '/asesor'
      fullPath: '/asesor'
      preLoaderRoute: typeof AsesorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sugerencias': {
      id: '/api/sugerencias'
      path: '/api/sugerencias'
      fullPath: '/api/sugerencias'
      preLoaderRoute: typeof ApiSugerenciasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AsesorRoute: AsesorRoute,
  ApiChatRoute: ApiChatRoute,
  ApiSearchRoute: ApiSearchRoute,
  ApiSugerenciasRoute: ApiSugerenciasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
